Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -49,7 +49,6 @@ mv $CACHE_DIR/$ARCHIVE_NAME/usr/ $BUILD_DIR/$ARCHIVE_NAME
 echo "almost done, after not using apt-get $ARCHIVE_NAME $BUILD_DIR/$ARCHIVE_NAME"
 echo "$BUILD_DIR= `ls -ltr $BUILD_DIR`"
 echo " contents of /$ARCHIVE_NAME is: `ls -ltr $BUILD_DIR/$ARCHIVE_NAME`"
-sed -i.bak 's/if ! which xauth >\/dev\/null; then error "xauth command not found" exit 3 fi//g' /home/vcap/app/xvfb/usr/bin/xvfb-run
 
 
 # --- perms cp cp  $BUILD_DIR/$ARCHIVE_NAME/usr/bin/* /usr/local/bin 
@@ -58,6 +57,7 @@ sed -i.bak 's/if ! which xauth >\/dev\/null; then error "xauth command not found
 cp $BUILD_DIR/$ARCHIVE_NAME/usr/bin/* /home/vcap/app/bin
 cd /home/vcap/app/bin
 echo " contents of /home/vcap/app/bin is: $(ls)"
+sed -i.bak 's/if ! which xauth >\/dev\/null; then error "xauth command not found" exit 3 fi//g' /home/vcap/app/xvfb/usr/bin/xvfb-run
 
 # export PATH="$BUILD_DIR/$ARCHIVE_NAME/usr/bin:/home/vcap/app/bin":$PATH
 # export PATH="$BUILD_DIR/$ARCHIVE_NAME"
