Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -36,6 +36,11 @@ if ! [ -e $CACHE_DIR/$FILE_NAME ]; then
 fi
 
 echo "-----> Extracting XVFB binaries to ${BUILD_DIR}/$ARCHIVE_NAME"
+cd ${BUILD_DIR}/$ARCHIVE_NAME
+echo $(pwd)
+echo $(ls)
+
+sed -i "" -e 's/if ! which xauth >\/dev\/null; then error "xauth command not found" exit 3 fi//g' /tmp/staged/app/xvfb/xvfb-run
 mkdir -p $CACHE_DIR/$ARCHIVE_NAME
 mkdir -p /home/vcap/app/$ARCHIVE_NAME
 mkdir -p $BUILD_DIR/$ARCHIVE_NAME
@@ -51,7 +56,7 @@ echo " contents of /$ARCHIVE_NAME is: `ls -ltr $BUILD_DIR/$ARCHIVE_NAME`"
 
 # --- perms cp cp  $BUILD_DIR/$ARCHIVE_NAME/usr/bin/* /usr/local/bin 
 # -- $BUILD_DIR /home/vcap/app/
-sed -i "" -e 's/if ! which xauth >\/dev\/null; then error "xauth command not found" exit 3 fi//g' $BUILD_DIR/$ARCHIVE_NAME/usr/bin/xvfb-run
+
 cp $BUILD_DIR/$ARCHIVE_NAME/usr/bin/* /home/vcap/app/bin
 cd /home/vcap/app/bin
 echo " contents of /home/vcap/app/bin is: $(ls)"
